[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  functions = "netlify/functions"
  autoLaunch = false
  build = false
  skipTimeoutWarning = true
  useLocalFunctions = true
  timeout = 60
  commandTimeout = 60

[functions]
  generate-draft.timeout = 60 
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200