name = "patent-generator-proxy"
main = "deepseek-proxy.js"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]  # Updated Node.js compatibility

# Simplified build configuration
[build]
command = "echo 'No build needed'"

# Explicit upload settings
[upload]
format = "service-worker"
dir = "cloudflare-worker"  # Point to worker directory
include = ["deepseek-proxy.js"]  # Only include necessary files

[dev]
port = 8787
ip = "localhost"

# Local development variables
[vars]
DEEPSEEK_API_KEY = "local_test_key_here"

# Production environment
[env.production]
name = "patent-generator-proxy-production"
workers_dev = true
account_id = "6bd724bb79ebfb6d4ea9d02114c49f04" 